// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBytmeHw775E9Ibi3NUdJGXSlXtCTaL-7Q',
    appId: '1:54163531168:android:55cf34ef9250af70adf0c5',
    messagingSenderId: '54163531168',
    projectId: 'chatapp-a9085',
    storageBucket: 'chatapp-a9085.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEsy-ggzv34oZkLegKpzkKDHxD9QeHqKM',
    appId: '1:54163531168:ios:b773d93134a5262aadf0c5',
    messagingSenderId: '54163531168',
    projectId: 'chatapp-a9085',
    storageBucket: 'chatapp-a9085.appspot.com',
    iosClientId: '54163531168-crnrbvjhltih55o69b0l3o1qfggtpvb6.apps.googleusercontent.com',
    iosBundleId: 'com.chatapp.app',
  );
}
